### ISSUE TITLE
Add support for discriminated `Union` types

### ISSUE THREAD

**Issue by bruno-f-cruz** [bonsai-rx/sgen#7]
`Union` present a particular challenge during deserialization as the type can only be inferred at runtime. Moreover, Json does not include a spec for the type of the object being deserialized and must often be inferred.

The suggestion is to leverage [`discriminated unions`](https://typethepipe.com/post/pydantic-discriminated-union/) and attempt to deserialize in runtime the objects. In order to integrate this strategy seamlessly with bonsai, an operator must be added that filters/convert each object in the collection to a specific given type thus allowing for polymorphic deserialization but maintaining the sequence data type.

**Comment by glopesdev** [comment]
@bruno-f-cruz we should confirm whether pydantic discriminated unions generate OpenAPI 3 compatible schemas. It looks like they should according to this PR: https://github.com/pydantic/pydantic/issues/619

This is important because OpenAPI 3 discriminators are what is supported by NJsonSchema according to their wiki: https://github.com/RicoSuter/NJsonSchema/wiki/Inheritance

Assuming this is the case, adding support for discriminators might still require a bit of work, since we ultimately need to support both JSON and YAML serialization. It looks like in both cases this will require generating additional helper code to help marshal types around:
- [JsonInheritanceConverter](https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.CSharp/Templates/JsonInheritanceConverter.liquid) and corresponding attribute (NJsonSchema)
- https://github.com/aaubry/YamlDotNet/issues/343

**Comment by glopesdev** [comment]
After further analysis there now seems to be an easier (in terms of infrastructure) option for YamlDotNet polymorphic deserialization: https://github.com/aaubry/YamlDotNet/pull/774

As for Newtonsoft.Json the best option for leveraging infrastructure would be to leverage [JsonSubTypes](https://www.nuget.org/packages/JsonSubTypes). This would require consumers to take in an extra dependency, but it seems to be the default choice as reusable infrastructure helper to implement discriminator based deserialization (40M+ downloads and long maintenance history).
