### ISSUE TITLE
Consider adding support of `EnumNames` or Enum: Object

### ISSUE THREAD

**Issue by bruno-f-cruz** [bonsai-rx/sgen#8]
json-schemas seems to allow enums to be defined as arrays of objects, eg:

```json
{
  "object": {
    "title": "object_title",
    "description": "desc",
    "enum": [
      {
        "name": "name1",
        "attr": "attr_value1"
      },
      {
        "name": "name2",
        "attr": "attr_value2"
      }
    ]
  }
}

```
Moreover, additional support from some standards have also added a way to use enumNames to refer to these enum entries:

```json
{
  "object": {
    "title": "object_title",
    "description": "desc",
    "enum": [
      {
        "name": "name1",
        "attr": "attr_value1"
      },
      {
        "name": "name2",
        "attr": "attr_value2"
      }
    ],
    "enumNames": ["name1", "name2"]
  }
}
```

Since csharp Enum only allow for numeric values, it would be great to implement a way to instantiate the enum name with the `enumNames` but still try to support the serialization/deserialization somehow.

**Comment by glopesdev** [comment]
@bruno-f-cruz This seems to be related to #11. I was checking some more examples of enum-like declarations in JSON-schema and to be honest they seem to be all over the place. As an example you can check the OpenAPI specification approach to labeled enums: https://github.com/OAI/OpenAPI-Specification/issues/348#issuecomment-336194030 where at least three different approaches to enum declaration are discussed and proposed.

If these patterns are something that NJsonSchema recognizes and can generate C# code for, then we can definitely modify and adapt the underlying model data structures. Otherwise I feel we should probably restrict ourselves to support only constructs that are compatible out-of-the-box with NJsonSchema, as we won't have the resources to diverge and maintain the foundations for a full-blown standards compliant parser/generator ourselves.

**Comment by bruno-f-cruz** [comment]
I completely agree, NJsonSchema already recognizes some of these patterns (e.g. https://github.com/RicoSuter/NJsonSchema/wiki/Enums). I would probably leave it "as is" if it is not too much work and if it doesn't break anything. We can think if we want to leverage a different behavior in the future. I would also agree with your general comment of being careful to not veer too far off from the NJsonSchema.

**Comment by glopesdev** [comment]
@bruno-f-cruz can you test if the modifications in #20 are acceptable to close this?
