### ISSUE TITLE
Implement `ICloneable` for sgen objects

### ISSUE THREAD

**Issue by bruno-f-cruz** [bonsai-rx/sgen#9]
This would allow to copy and modify fields easily.

**Comment by glopesdev** [comment]
Implementing `ICloneable` is now [actively discouraged in the MSDN reference manual](https://learn.microsoft.com/en-us/dotnet/api/system.icloneable?view=net-8.0#notes-to-implementers). The reason seems to be ambiguity around whether `Clone` should perform a deep or shallow copy.

For C# record types the auto-generated implementation now provides a shallow-copy constructor and a new `with` operator which allows creating modified copies of existing record objects.

#15 and #13 provide the first half of such an implementation, by introducing copy constructors for all generated classes and an overload for triggering copy on input. This allows using the `InputMapping` operator to pull any desired properties from the input, while allowing specification of other properties.

Later we can take this approach one step further either by making the copy constructor public, or exposing a `Copy` method to allow emulating something similar to the `with` operator. At the moment I feel we should experiment a bit first with the workflow-based functionality to get a better feel about future requirements before committing one way or the other.

**Comment by glopesdev** [comment]
Closing this for now in favor of #13.
